### ISSUE TITLE
Final Capstone Project Kanban Board

### ISSUE THREAD

**Issue by toliboff** [andersonlebon/Final-Capstone-backend#28]
Here is the link to the project [kanban board](https://github.com/andersonlebon/Final-Capstone-backend/projects/1)
We are three in this team:  
- [ ] Team member A is @pasytchangwa
- [ ] Team member B is @toliboff
- [ ] Team member C is @andersonlebon

Kanban board initial screenshot
![kanban_screenshot](https://user-images.githubusercontent.com/24884414/145537271-8e02f6be-9de0-4449-a1df-e7c6208617c9.png)

![kanban_screenshot_1](https://user-images.githubusercontent.com/24884414/145537788-4ec1e718-0514-469d-ba55-0ea658fc4c6a.png)

![kanban_screenshot_2](https://user-images.githubusercontent.com/24884414/145537800-15423f56-59d3-4cb5-bd05-f4d01823d71e.png)

![kanban_screenshot_3](https://user-images.githubusercontent.com/24884414/145537819-5ff109a8-fbb9-47e7-a30b-833ded93951e.png)

![kanban_screenshot_4](https://user-images.githubusercontent.com/24884414/145537833-143bf12f-e4b4-458f-a310-5b5a557ba3c9.png)

![kanban_screenshot_5](https://user-images.githubusercontent.com/24884414/145537851-c81cdbc9-982f-40b3-a5ae-8315132d2ce9.png)

**Comment by christianotieno** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Apologies for the late feedback from me. It was not intentional. 🙏🏾 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
